require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude: 
  - 'lib/codebreaker_gem/game.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
  - 'spec/**/*.rb'
